### ISSUE TITLE
你好为什么屏蔽libc.so

### ISSUE THREAD

**Issue by chongbo2013** [zkwlx/HiMem#2]
xhook_ignore(".*libc.so$", "free");
    xhook_ignore(".*libc.so$", "malloc");
    xhook_ignore(".*libc.so$", "calloc");
    xhook_ignore(".*libc.so$", "realloc");

**Comment by zkwlx** [comment]
出于性能考虑，malloc 的调用太过频繁

**Comment by chongbo2013** [comment]
@zkwlx 我这边hook so 发现在别的so mmap 30mb，libc也会增加10,请问下放开so后，如何才能比较准确

**Comment by chongbo2013** [comment]
还有malloc 分配大内存会自动切 mmap

**Comment by zkwlx** [comment]
印象中 malloc 超过128KB 就会使用 mmap，所以我们这边主要是 hook mmap。
要想 100% hook 的话使用 inline hook 会比较好，直接 hook 调大家调用的 libc 中的 mmap

**Comment by chongbo2013** [comment]
inline hook估计不好实现，实时获取so 数据，我发现xhook只要hook的数量多 就容易卡死，比如 egl等，大佬有啥方案吗

**Comment by zkwlx** [comment]
卡死我确实没遇到过，不过建议替换成 bhook，整体方案优化了很多

**Comment by chongbo2013** [comment]
就是不支持armeabi我们32还在用
